//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCCSS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expedientes
    {
        public int ID_Expediente { get; set; }
        public Nullable<int> ID_Paciente { get; set; }
        public Nullable<int> ID_Medico { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string Resultados_Pruebas { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
    
        public virtual PersonalMedico PersonalMedico { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
